### ISSUE TITLE
Support S3 bucket encryption

### ISSUE THREAD

**Issue by abessifi** [awslabs/aws-servicebroker#102]
**User story**

As a OpenShift/Kubernetes user, I want that AWS Broker support S3 bucket encryption so that the created S3 bucket is secured.

**Describe the solution you'd like**

Default behaviour: Encryption disable.
Type of encryption when enabled: Server-Side encryption `AES-256`.

**Additional context**

More about the feature: https://docs.aws.amazon.com/AmazonS3/latest/dev/bucket-encryption.html

**Comment by abessifi** [comment]
This can be done using custom cloudformation template but it is better to include the encryption option in the default template with parameters. Example of a snippet config I've used:

```yaml
[...]
Resources:
  S3bucket:
    Type: AWS::S3::Bucket
    Properties:
      [...]
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
[...]
```
