### ISSUE TITLE
Can't Get the DynamoDB to rebuild data

### ISSUE THREAD

**Issue by kferrone** [awslabs/aws-servicebroker#184]
**Describe the bug**
So I switched from the default s3 bucket which the broker uses called `awsservicebroker` and rolled out my own so I can make a custom template. I added a custom template based on the `elasticache-main.yaml`, in an attempt to make it use redis. 

My first mess up, I forgot to rename it . . . First my error was it could not find the s3 key in my bucket. I realized it had something to do with the data in dynamodb. I renamed the class to `elasticache-redis` and renamed the file to `elasticache-redis.yaml`.  Then it could not find the class at all when I ran my lil test file. I thought maybe deleting the data in the DynamoDB, deleting the service-broker helm release, and even deleting the svc-cat helm release would maybe get things working . . . this did nothing but give me the same error after reinstalling the charts again. 

 It feels like something is left behind after uninstall and reinstall sees this info???

How to get the DynamoDB table repopulate?

**To Reproduce**
 - rerun broker chart with new s3 bucket which has new template
 - delete all data in the DynamoDB
 - try running a service using your new template from new s3 bucket

**Expected behavior**
After complete reinstall of broker I expected the DynamoDB table would be repopulated. 

**Environment:**
 - Application Platform: Kubernetes (aws/eks)
 - Application Platform Version:  k8s 1.14.0
 - Broker Version: 1.0.1 helm chart

**Additional context**

Here is the error from running: 
`kubectl get ServiceInstance/elastic-redis -n default -o yaml`
```
'The instance references a ClusterServiceClass that does not exist. References
  a non-existent ClusterServiceClass {ClusterServiceClassExternalName:"elasticache-redis"}
  or there is more than one (found: 0)'
```

Here is my sample manifest:
```
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: elastic-redis
  namespace: default
spec:
  clusterServiceClassExternalName: elasticache-redis
  clusterServicePlanExternalName: production
  parameters:
    AccessCidr: 0.0.0.0/0
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: elastic-redis-binding
  namespace: default
spec:
  instanceRef:
    name: elastic-redis
```

I also see this output in the broker pod itself:
```
I0221 23:26:24.990430       1 awsbroker.go:174] Listing objects bucket: my-template-repo region: us-west-2 prefix: templates
I0221 23:26:25.100421       1 awsbroker.go:193] Found 0 objects
I0221 23:26:25.100441       1 awsbroker.go:168] Updating listings cache with []
I0221 23:36:24.990575       1 awsbroker.go:174] Listing objects bucket: my-template-repo region: us-west-2 prefix: templates
I0221 23:36:25.036905       1 awsbroker.go:193] Found 0 objects
I0221 23:36:25.036928       1 awsbroker.go:168] Updating listings cache with []
```
I figured this was permissions on the file but it is public readonly on the s3 bucket???
