### ISSUE TITLE
[Doc bug] There is no obvious documentation of the helm chart

### ISSUE THREAD

**Issue by iMartyn** [awslabs/aws-servicebroker#185]
**Describe the bug**
The [getting started k8s](https://github.com/awslabs/aws-servicebroker/blob/master/docs/getting-started-k8s.md) tells you where to install the chart from, and it states you should "Add flags to set credentials, region, etc" but there is no documentation saying what values to change to do this.

**To Reproduce**
Attempt to set up `aws-servicebroker` on a non-aws k8s cluster (e.g. GKE or minikube etc) by following the getting started guide.

**Expected behavior**
Some kind of documentation on how to configure the helm chart. e.g. https://hub.helm.sh/charts/stable/cluster-autoscaler gives a lot, but even just replicating the Configuration section would be enough to get up and running.

**Screenshots**
https://github.com/awslabs/aws-servicebroker/blob/a3febc709e7f51ced48c244bbb96efa7cbc9e2cb/docs/getting-started-k8s.md

**Environment (please complete the following information):**
 - Application Platform: Kubernetes
 - Application Platform Version: any
 - Broker Version any

**Additional context**
I can perhaps download the chart and try and figure out values that way but really, there should be a page describing the values, their defaults and what they do.

**Comment by iMartyn** [comment]
In case anyone wants to know the basic details, `helm show values awssb/aws-servicebroker` yeilds : 
```
image: awsservicebroker/aws-servicebroker:beta
imagePullPolicy: Always
authenticate: true
tls:
  cert:
  key:
deployClusterServiceBroker: true
deployNamespacedServiceBroker: false
aws:
  region: us-east-1
  bucket: awsservicebroker
  key: templates/latest
  s3region: us-east-1
  tablename: awssb
  accesskeyid: ""
  secretkey: ""
  targetaccountid: ""
  targetrolename: ""
  vpcid: ""
brokerconfig:
  verbosity: 10
  brokerid: awsservicebroker
  prescribeoverrides: true
annotations: {}
clusterDomain: cluster.local
```

So that gives a very rough idea of how to set the values, but doesn't indicate what is optional/required or any real clue as to what the values should be in your setup.
