### ISSUE TITLE
Cant create Fifo queues 

### ISSUE THREAD

**Issue by rafilkmp3** [awslabs/aws-servicebroker#239]
**Describe the bug**
Its impossible create fifo queues 

**To Reproduce**
create a file with example https://github.com/awslabs/aws-servicebroker/blob/master/templates/sqs/README.md#complete-1
 
```
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: sqs-fifo-complete-example
spec:
  clusterServiceClassExternalName: sqs
  clusterServicePlanExternalName: fifo
  parameters:
    ContentBasedDeduplication: true # OPTIONAL
    DelaySeconds: 5 # OPTIONAL
    MaximumMessageSize: 262144 # OPTIONAL
    MessageRetentionPeriod: 345600 # OPTIONAL
    ReceiveMessageWaitTimeSeconds: 0 # OPTIONAL
    UsedeadletterQueue: false # OPTIONAL
    VisibilityTimeout: 5 # OPTIONAL

```
kubectl appy -f fifo-queue.yaml

**Expected behavior**
fifo queue created 

**Screenshots**
![image](https://user-images.githubusercontent.com/12433667/115917288-5ece9a00-a44c-11eb-90ce-3a7fda2b7c23.png)

**Environment (please complete the following information):**
 - Application Platform: Kubernete eks]
 - Application Platform Version: [ k8s 1.19]
 - Broker Version "1.0.3"

**Additional context**
Its related with #197
