### ISSUE TITLE
Allow Custom Tags to be Added to Provisioned Resources

### ISSUE THREAD

**Issue by ricfeatherstone** [awslabs/aws-servicebroker#68]
Many Enterprises use custom tags on AWS Resources for a number of different purposes e.g. internal billing, access control etc.

It would be nice to be able specify custom tags to be added to resources when provisioning.

A blanket set of additional tags would be a great start but it would be nice to be able to have different tags with a namespace / project. Taking this further you could set the base tags in the broker and add additional tags, or override tag values at the project level.

**Comment by jaymccon** [comment]
Tags with the cluster_id (or org for cloud foundry), namespace, broker_id and instance_id are already automatically applied to stacks. Working on getting some slots for custom tags

**Comment by jaymccon** [comment]
Added 2 global parameters that accepts a json list of tags in the format:
```json
[
  {
    "Key": "MyTag1",
    "Value": "MyValue"
  },
  {
    "Key": "MyTag2",
    "Value": "MyValue"
  }
]
```

The idea behind having 2 parameters is that `admin_tags` can be overridden at a project/cluster level, and `user_tags` will be left for the user to specify when they make the provision call.

@ricfeatherstone thoughts ?

**Comment by ricfeatherstone** [comment]
Personally I'd prefer a more succinct `key: value` definition but what you've got matches the more verbose AWS model. How would this look in a K8S Resource using Yaml? 

```
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: s3-custom-minimal-example
spec:
  clusterServiceClassExternalName: s3
  clusterServicePlanExternalName: custom
  parameters:
    user_tags: '[{"Key": "MyTag1","Value": "MyValue"},{"Key": "MyTag2","Value": "MyValue"}]'
```

It's not as nice as

```
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: s3-custom-minimal-example
spec:
  clusterServiceClassExternalName: s3
  clusterServicePlanExternalName: custom
  parameters:
    user_tags: 
    - MyTag1: MyValue
    - MyTag2: MyValue
```

but it's not the end of the world. 

I guess the Json would fit better when being stored in the metadata table for defaults / overrides.

What is the behaviour if `admin_tags` and `user_tags` specify the same Key?

Can these be specified as Environment Variables on the Broker Deployment?

I'll have to get a Docker environment supporting multi-stage builds to create the image to test this as it's not on docker hub. I'll let you know how I get on
